export const storiesData = [
  {
    id: 'my-story',
    username: 'Seu story',
    avatar: '/images/eu.jpeg',
    isOwn: true,
    isViewed: false,
  },
  {
    id: 'story-1',
    username: 'matheus_gay',
    avatar: '/images/matheus.jpeg',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-2',
    username: 'marcelo_careca',
    avatar: '/images/marcelo.jpeg',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-3',
    username: 'gio_alves',
    avatar: '/images/gio2.jpeg',
    isOwn: false,
    isViewed: true,
  },
  {
    id: 'story-4',
    username: 'leo_down',
    avatar: '/images/leo.jpeg',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-5',
    username: 'thiagones',
    avatar: 'images/thiago.jpeg',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-6',
    username: 'cristian_biasi',
    avatar: 'images/cristaldo.jpeg',
    isOwn: false,
    isViewed: true,
  },
];

export const postsData = [
  {
    id: 'post-1',
    user: 'gio_alves',
    avatar: '/images/gio2.jpeg',
    image: '/images/giovani.png',
    likedBy: 'ana_silva',
    likesCount: 42,
    caption: '🌞 समुद्र तट पर एक परफेक्ट दिन! सूरज शानदार था और पानी बिल्कुल साफ़। दोस्तों के साथ समय बिताना बहुत अच्छा लगा। #समुद्रतट #गर्मी #दोस्त #मज़ा',
    time: 'há 2 horas',
    comments: [
      { user: 'marcelo_careca', text: 'Indiano, fedorento! 😍' },
      { user: 'lucao_avelino', text: 'Cheiro de rato daqui' },
    ],
  },
  {
    id: 'post-2',
    user: 'cristiano',
    avatar: 'images/cr71.jpg',
    image: 'images/eucr7.png',
    likedBy: 'neymarjr',
    likesCount: 28,
    caption: 'Eu e meu grande amigo Lucão, ídolo máximo! Sempre uma honra compartilhar momentos com você. @lucao_avelino #amizade #ídolo #gratidão ',
    time: 'há 4 horas',
    comments: [
      { user: 'lucao_avelino', text: 'Você é o maior! Ídolo!' },
      { user: 'ana_silva', text: 'top demais!' },
    ],
  },
  {
    id: 'post-3',
    user: 'giorgian_arrascaeta',
    avatar: 'images/arrasca.jpg',
    image: 'images/euarrasc.png',
    likedBy: 'gabigol',
    likesCount: 156,
    caption: 'Meu grande amigo, @lucao_avelino, conquistando mais um título com muita garra e determinação. Você é uma inspiração para todos nós! #campeão #determinação #inspiração',
    time: 'há 6 horas',
    comments: [
      { user: 'lucia_ferreira', text: 'Parabéns! Você merece!' },
      { user: 'pedro_costa', text: 'Incrível trabalho!' },
      { user: 'ana_silva', text: 'Que orgulho! 👏' },
    ],
  },
  {
    id: 'post-4',
    user: 'vampeta',
    avatar: 'images/vamp.webp',
    image: 'images/vampeta-g-magazine.jpg',
    likedBy: 'lucia_ferreira',
    likesCount: 89231,
    caption: 'Passeio matinal pelo parque. A natureza sempre me renova a energia. #natureza #paz #manhã',
    time: 'há 8 horas',
    comments: [
      { user: 'maria_santos', text: 'Que lugar lindo!' },
    ],
  },
  {
    id: 'post-5',
    user: 'popebenedictxvi',
    avatar: 'images/pope2.jpg',
    image: 'images/pope.jpeg',
    likedBy: 'lucao_avelino',
    likesCount: 73232,
    caption: 'Hoje é dia de cerveja!',
    time: 'há 12 horas',
    comments: [
      { user: 'lucao_avelino', text: 'Isso ai grande Doutor da Igreja!' },
      { user: 'segundocatolico', text: 'O senhor merece!' },
    ],
  },
];

