export const storiesData = [
  {
    id: 'my-story',
    username: 'Seu story',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isOwn: true,
    isViewed: false,
  },
  {
    id: 'story-1',
    username: 'ana_silva',
    avatar: 'https://i.pravatar.cc/150?img=2',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-2',
    username: 'carlos_mendes',
    avatar: 'https://i.pravatar.cc/150?img=3',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-3',
    username: 'maria_santos',
    avatar: 'https://i.pravatar.cc/150?img=4',
    isOwn: false,
    isViewed: true,
  },
  {
    id: 'story-4',
    username: 'joao_oliveira',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-5',
    username: 'lucia_ferreira',
    avatar: 'https://i.pravatar.cc/150?img=6',
    isOwn: false,
    isViewed: false,
  },
  {
    id: 'story-6',
    username: 'pedro_costa',
    avatar: 'https://i.pravatar.cc/150?img=7',
    isOwn: false,
    isViewed: true,
  },
];

export const postsData = [
  {
    id: 'post-1',
    user: 'ana_silva',
    avatar: 'https://i.pravatar.cc/150?img=2',
    image: 'https://picsum.photos/seed/post1/1080/1080',
    likedBy: 'ana_silva',
    likesCount: 42,
    caption: 'Um dia perfeito na praia! O sol estava incrível e a água estava cristalina. Adorei passar o tempo aqui com os amigos. #praia #verão #amigos #diversão',
    time: 'há 2 horas',
    comments: [
      { user: 'carlos_mendes', text: 'Que foto linda! 😍' },
      { user: 'maria_santos', text: 'Quero ir também!' },
    ],
  },
  {
    id: 'post-2',
    user: 'carlos_mendes',
    avatar: 'https://i.pravatar.cc/150?img=3',
    image: 'https://picsum.photos/seed/post2/1080/1080',
    likedBy: 'maria_santos',
    likesCount: 28,
    caption: 'Novo café que abriu na cidade. O ambiente é super aconchegante e o café está delicioso! Recomendo muito.',
    time: 'há 4 horas',
    comments: [
      { user: 'ana_silva', text: 'Onde fica esse café?' },
    ],
  },
  {
    id: 'post-3',
    user: 'maria_santos',
    avatar: 'https://i.pravatar.cc/150?img=4',
    image: 'https://picsum.photos/seed/post3/1080/1080',
    likedBy: 'joao_oliveira',
    likesCount: 156,
    caption: 'Finalmente terminei meu projeto! Foi um trabalho árduo mas valeu a pena. Agora é só comemorar! 🎉',
    time: 'há 6 horas',
    comments: [
      { user: 'lucia_ferreira', text: 'Parabéns! Você merece!' },
      { user: 'pedro_costa', text: 'Incrível trabalho!' },
      { user: 'ana_silva', text: 'Que orgulho! 👏' },
    ],
  },
  {
    id: 'post-4',
    user: 'joao_oliveira',
    avatar: 'https://i.pravatar.cc/150?img=5',
    image: 'https://picsum.photos/seed/post4/1080/1080',
    likedBy: 'lucia_ferreira',
    likesCount: 89,
    caption: 'Passeio matinal pelo parque. A natureza sempre me renova a energia. #natureza #paz #manhã',
    time: 'há 8 horas',
    comments: [
      { user: 'maria_santos', text: 'Que lugar lindo!' },
    ],
  },
  {
    id: 'post-5',
    user: 'lucia_ferreira',
    avatar: 'https://i.pravatar.cc/150?img=6',
    image: 'https://picsum.photos/seed/post5/1080/1080',
    likedBy: 'pedro_costa',
    likesCount: 73,
    caption: 'Jantar especial com a família. Esses momentos são os melhores da vida. Gratidão por ter pessoas tão especiais ao meu lado.',
    time: 'há 12 horas',
    comments: [
      { user: 'ana_silva', text: 'Que família linda! ❤️' },
      { user: 'carlos_mendes', text: 'Momento perfeito!' },
    ],
  },
];

